/* ═══════════════════════════════════════════════════════════
   words.js — Imposter Game word database (Categorized)
   Each entry: [ secretWord, imposterHint ]
   The hint is related but vague enough that the Imposter
   can participate without knowing the exact secret word.
═══════════════════════════════════════════════════════════ */

const WORD_DB = [
  // ─── FOOD & DRINK ───────────────────────────────────────
  ["Apple",           "Red"],
  ["Ice Cream",       "Cold"],
  ["Pizza",           "Cheese"],
  ["Chocolate",       "Sweet"],
  ["Bakery",          "Bread"],
  ["Dessert",         "Sugar"],
  ["Noodles",         "Soup"],
  ["Apricot",         "Fruit"],
  ["Grapes",          "Vine"],
  ["Restaurant",      "Food"],
  ["Coffee",          "Morning"],
  ["Tea",             "Drink"],
  ["Water",           "Thirst"],
  ["Egg",             "Breakfast"],
  ["Pancake",         "Breakfast"],
  ["Burger",          "Fast Food"],
  ["Sandwich",        "Lunch"],
  ["Sushi",           "Rice"],
  ["Dumpling",        "Stuffed"],
  ["Popcorn",         "Movie"],
  ["Cupcake",         "Frosting"],
  ["Milkshake",       "Creamy"],
  ["Croissant",       "Pastry"],
  ["Waffle",          "Syrup"],
  ["Spaghetti",       "Sauce"],
  ["Salad",           "Bowl"],
  ["Cookie",          "Bake"],
  ["Hot Dog",         "Mustard"],
  ["French Fries",    "Potato"],
  ["Cheese",          "Slice"],
  ["Pop Soda",        "Bubbles"],
  ["Juice",           "Fruit"],

  // ─── VEGETABLES & FRUITS ────────────────────────────────
  ["Pumpkin",         "Harvest"],
  ["Carrot",          "Orange"],
  ["Broccoli",        "Green"],
  ["Watermelon",      "Summer"],
  ["Banana",          "Yellow"],
  ["Strawberry",      "Small"],
  ["Cherry",          "Fruit"],
  ["Lemon",           "Sour"],
  ["Coconut",         "Tropical"],

  // ─── ANIMALS & INSECTS ──────────────────────────────────
  ["Penguin",         "Ice"],
  ["Safari",          "Animals"],
  ["Shark",           "Ocean"],
  ["Octopus",         "Tentacles"],
  ["Dolphin",         "Leap"],
  ["Whale",           "Giant"],
  ["Seal",            "Arctic"],
  ["Peacock",         "Feathers"],
  ["Falcon",          "Hunt"],
  ["Parrot",          "Talk"],
  ["Nest",            "Eggs"],
  ["Beehive",         "Honey"],
  ["Butterfly",       "Wings"],
  ["Cocoon",          "Transform"],
  ["Ant",             "Colony"],
  ["Spider",          "Web"],
  ["Camel",           "Desert"],
  ["Zebra",           "Stripes"],
  ["Gorilla",         "Jungle"],
  ["Panda",           "Bamboo"],
  ["Koala",           "Australia"],
  ["Kangaroo",        "Jump"],
  ["Raccoon",         "Mask"],
  ["Hedgehog",        "Spikes"],
  ["Rabbit",          "Hop"],
  ["Squirrel",        "Nuts"],
  ["Alligator",       "Swamp"],
  ["Beaver",          "Dam"],
  ["Chameleon",       "Color"],
  ["Cheetah",         "Fast"],
  ["Crow",            "Black"],
  ["Deer",            "Antlers"],
  ["Dragonfly",       "Insect"],
  ["Eagle",           "Soar"],
  ["Fox",             "Clever"],
  ["Frog",            "Pond"],
  ["Gecko",           "Lizard"],
  ["Giraffe",         "Neck"],
  ["Goldfish",        "Bowl"],
  ["Goose",           "Honk"],
  ["Jellyfish",       "Tentacles"],
  ["Leopard",         "Danger"],
  ["Chicken",         "Farm"],
  ["Dog",             "Pet"],
  ["Cat",             "Pet"],
  ["Horse",           "Ride"],
  ["Tiger",           "Stripes"],
  ["Elephant",        "Trunk"],
  ["Monkey",          "Banana"],
  ["Fish",            "Water"],
  ["Bird",            "Fly"],

  // ─── NATURE, LANDSCAPES & GEOGRAPHY ─────────────────────
  ["Beach",           "Ocean"],
  ["Mountain",        "Tall"],
  ["Forest",          "Trees"],
  ["Volcano",         "Lava"],
  ["Thunder",         "Storm"],
  ["Tornado",         "Wind"],
  ["Jungle",          "Wild"],
  ["Rainbow",         "Colors"],
  ["Snowflake",       "Winter"],
  ["Cactus",          "Desert"],
  ["Glacier",         "Frozen"],
  ["Waterfall",       "Cascade"],
  ["Canyon",          "Cliff"],
  ["Oasis",           "Water"],
  ["Mushroom",        "Forest"],
  ["River",           "Flow"],
  ["Lake",            "Blue or Green"],
  ["Island",          "Surrounded"],
  ["Cave",            "Dark"],
  ["Cliff",           "Edge"],
  ["Valley",          "Between"],
  ["Hill",            "Slope"],
  ["Swamp",           "Mud"],
  ["Geyser",          "Steam"],
  ["Avalanche",       "Snow"],
  ["Bamboo",          "Panda"],
  ["Boulder",         "Rock"],
  ["Cyclone",         "Storm"],
  ["Earthquake",      "Shake"],
  ["Echo",            "Repeat"],
  ["Fog",             "Mist"],
  ["Horizon",         "Distance"],
  ["Hurricane",       "Cyclone"],
  ["Iceberg",         "Hidden"],

  // ─── SPACE & SCIENCE ────────────────────────────────────
  ["Astronaut",       "Space"],
  ["Meteor",          "Sky"],
  ["Comet",           "Tail"],
  ["Rocket",          "Launch"],
  ["Satellite",       "Orbit"],
  ["Planet",          "Solar"],
  ["Galaxy",          "Stars"],
  ["Black Hole",      "Gravity"],
  ["Orbit",           "Circle"],
  ["Laboratory",      "Experiment"],
  ["Scientist",       "Research"],
  ["Magnet",          "Attract"],
  ["Electricity",     "Current"],
  ["Microscope",      "Tiny"],
  ["Telescope",       "Stars"],
  ["Eclipse",         "Shadow"],

  // ─── SPORTS, GAMES & HOBBIES ────────────────────────────
  ["Soccer",          "Ball"],
  ["Skateboard",      "Wheels"],
  ["Bicycle",         "Pedal"],
  ["Volleyball",      "Net"],
  ["Basketball",      "Hoop"],
  ["Tennis",          "Racket"],
  ["Baseball",        "Bat"],
  ["Hockey",          "Ice"],
  ["Boxing",          "Gloves"],
  ["Medal",           "Winner"],
  ["Trophy",          "Champion"],
  ["Referee",         "Rules"],
  ["Stadium",         "Crowd"],
  ["Maze",            "Puzzle"],
  ["Chess",           "Strategy"],
  ["Dice",            "Roll"],
  ["Puzzle",          "Pieces"],
  ["Javelin",         "Throw"],
  ["Jigsaw",          "Puzzle"],
  ["Jungle Gym",      "Playground"],
  ["Deck",            "Cards"],
  ["Domino",          "Tiles"],
  ["Chessboard",      "Squares"],
  ["Bowling",         "Pins"],
  ["Golf",            "Club"],
  ["Skating Rink",    "Ice"],
  ["Skis",            "Snow"],
  ["Surfboard",       "Wave"],
  ["Running Shoes",   "Feet"],
  ["Fishing Rod",     "Catch"],
  ["Gym",             "Workout"],
  ["Yoga",            "Stretch"],

  // ─── ENTERTAINMENT, TOYS & RECREATION ───────────────────
  ["Cinema",          "Popcorn"],
  ["Carnival",        "Fun"],
  ["Kite",            "Fly"],
  ["Puppet",          "Strings"],
  ["Fossil",          "Ancient"],
  ["Sandcastle",      "Shore"],
  ["Joystick",        "Control"],
  ["Ferris Wheel",    "Disneyland"],
  ["Clown",           "Circus"],
  ["Jukebox",         "Music"],
  ["Amusement Park",  "Ride"],
  ["Zoo",             "Cage"],
  ["Video Game",      "Controller"],
  ["Party",           "Friends"],
  ["Birthday",        "Cake"],
  ["Gift",            "Present"],
  ["Vacation",        "Holiday"],
  ["Beach Ball",      "Summer"],
  ["Swimming Pool",   "Water"],
  ["Camping",         "Tent"],
  ["Picnic",          "Basket"],
  ["Barbecue",        "Grill"],
  ["Playground",      "Slide"],

  // ─── MUSIC, ARTS & MEDIA ────────────────────────────────
  ["Guitar",          "Music"],
  ["Violin",          "Strings"],
  ["Drum",            "Beat"],
  ["Trumpet",         "Brass"],
  ["Piano",           "Keys"],
  ["Opera",           "Stage"],
  ["Microphone",      "Voice"],
  ["Singer",          "Music"],
  ["Actor",           "Movie"],
  ["Popstar",         "Stage"],
  ["Photograph",      "Memory"],
  ["Guitar Pick",     "Strum"],
  ["Harp",            "Strings"],

  // ─── TECHNOLOGY, COMPUTERS & GADGETS ────────────────────
  ["Keyboard",        "Typing"],
  ["Projector",       "Presentation"],
  ["Headphones",      "Audio"],
  ["Speaker",         "Sound"],
  ["Camera",          "Lens"],
  ["Drone",           "Remote"],
  ["Battery",         "Power"],
  ["Laptop",          "Portable"],
  ["Monitor",         "Display"],
  ["Mouse",           "Cursor"],
  ["Printer",         "Paper"],
  ["Router",          "Internet"],
  ["Server",          "Network"],
  ["Password",        "Security"],
  ["Website",         "Online"],
  ["Application",     "Software"],
  ["Robot Vacuum",    "Cleaning"],
  ["Robot",           "Machine"],
  ["Phone",           "Call"],
  ["Television",      "Screen"],
  ["Computer",        "Internet"],
  ["Smart Watch",     "Wrist"],
  ["Tablet",          "Screen"],
  ["Wi-Fi",           "Signal"],
  ["Bluetooth",       "Wireless"],
  ["Selfie",          "Camera"],
  ["Emoji",           "Face"],

  // ─── SCHOOL, OFFICE & BOOKS ─────────────────────────────
  ["Library",         "Books"],
  ["Notebook",        "Pages"],
  ["Backpack",        "School"], // Deduplicated attributes internally
  ["Chalk",           "Board"],
  ["Marker",          "Ink"],
  ["Calculator",      "Math"],
  ["Bookmark",        "Page"],
  ["Dictionary",      "Words"],
  ["Globe",           "World"],
  ["Exam",            "Test"],
  ["Homework",        "Assignment"],
  ["Diploma",         "Graduate"],
  ["Uniform",         "School"],
  ["Locker",          "Storage"],
  ["Calendar",        "Dates"],
  ["Diary",           "Journal"],
  ["Envelope",        "Letter"],
  ["Journal",         "Writing"],
  ["School",          "Students"],
  ["Teacher",         "Classroom"],
  ["Student",         "Learning"],
  ["Office",          "Work"],
  ["Boss",            "Manager"],
  ["Scissors",        "Cut"],
  ["Tape",            "Sticky"],
  ["Glue",            "Paper"],
  ["Crayon",          "Color"],

  // ─── MEDICAL & HEALTH ───────────────────────────────────
  ["Hospital",        "Medicine"],
  ["Ambulance",       "Emergency"],
  ["Doctor",          "Treatment"],
  ["Nurse",           "Care"],
  ["Pharmacy",        "Prescription"],
  ["Stethoscope",     "Heartbeat"],
  ["X-Ray",           "Bones"],
  ["Band-Aid",        "Cut"],

  // ─── LAW, CRIME & MYSTERY ───────────────────────────────
  ["Treasure Map",    "Clue"],
  ["Spy",             "Secret"],
  ["Detective",       "Investigation"],
  ["Fingerprint",     "Evidence"],
  ["Magnifying Glass","Search"],
  ["Vault",           "Secure"],
  ["Prison",          "Bars"],
  ["Courtroom",       "Judge"],
  ["Judge",           "Law"],
  ["Lawyer",          "Case"],
  ["Police",          "Patrol"],

  // ─── TRANSPORTATION & TRAVEL ────────────────────────────
  ["Train",           "Railway"],
  ["Submarine",       "Underwater"],
  ["Passport",        "Travel"],
  ["Suitcase",        "Pack"],
  ["Helicopter",      "Rotor"],
  ["Airport",         "Flights"],
  ["Runway",          "Takeoff"],
  ["Taxi",            "Fare"],
  ["Bus",             "Route"],
  ["Motorcycle",      "Helmet"],
  ["Scooter",         "Ride"],
  ["Traffic Light",   "Signal"],
  ["Tunnel",          "Underground"],
  ["Highway",         "Travel"],
  ["Fuel",            "Engine"],
  ["Cockpit",         "Pilot"],
  ["Conductor",       "Train"],
  ["Escalator",       "Steps"],
  ["Ferry",           "Crossing"],
  ["Hangar",          "Aircraft"],
  ["Hot Air Balloon", "Basket"],
  ["Jet",             "Speed"],
  ["Parachute",       "Sky"],
  ["Hotel",           "Travel"],
  ["Headlights",      "Night"],
  ["Subway",          "Station"],
  ["Taxi Cab",        "Yellow"],
  ["Traffic Jam",     "Cars"],
  ["Gas Station",     "Pump"],
  ["Parking Lot",     "Spaces"],

  // ─── MARITIME & NAVAL ───────────────────────────────────
  ["Anchor",          "Ship"],
  ["Harbor",          "Dock"],
  ["Pirate",          "Ship"],
  ["Dock",            "Boat"],
  ["Helm",            "Captain"],
  ["Lifeboat",        "Rescue"],
  ["Cruise Ship",     "Ocean"],

  // ─── BUILDINGS, ARCHITECTURE & HOME STRUCTURES ──────────
  ["Pyramid",         "Egypt"],
  ["Elevator",        "Floor"],
  ["Fountain",        "Water"],
  ["Bridge",          "River"],
  ["Museum",          "History"],
  ["Basement",        "Below"],
  ["Chandelier",      "Ceiling"],
  ["Chimney",         "Smoke"],
  ["Cupboard",        "Kitchen"],
  ["Curtain",         "Window"],
  ["Doorbell",        "Visitor"],
  ["Dresser",         "Clothes"],
  ["Farmhouse",       "Rural"],
  ["Fence",           "Boundary"],
  ["Garage",          "Vehicle"],
  ["Greenhouse",      "Plants"],
  ["Keyhole",         "Lock"],
  ["Skyscraper",      "City"],
  ["Street Lamp",     "Sidewalk"],
  ["Park Bench",      "Sit"],

  // ─── HISTORY, ROYALTY & MYTHOLOGY ───────────────────────
  ["Castle",          "King"],
  ["Palace",          "Royal"],
  ["Crown",           "King"],
  ["Shield",          "Defense"],
  ["Sword",           "Battle"],
  ["Bow",             "Arrow"],
  ["Arrow",           "Target"],
  ["Helmet",          "Protection"],
  ["Banner",          "Flag"],
  ["Empire",          "Nation"],
  ["Armor",           "Protection"],
  ["Drawbridge",      "Castle"],
  ["Vampire",         "Night"],
  ["Dragon",          "Fire"],
  ["Wizard",          "Magic"],
  ["Knight",          "Armor"],
  ["Mermaid",         "Sea"],
  ["Unicorn",         "Horn"],
  ["Superhero",       "Cape"],

  // ─── CITY, CULTURE & RELIGION ───────────────────────────
  ["Village",         "Small"],
  ["Market",          "Trade"],
  ["Temple",          "Prayer"],
  ["Bell",            "Ring"],
  ["Statue",          "Stone"],
  ["Monument",        "Memory"],
  ["Festival",        "Celebration"],
  ["Fireworks",       "Celebrate"],

  // ─── HOUSEHOLD APPLIANCES & ITEMS ───────────────────────
  ["Fireplace",       "Warm"],
  ["Candle",          "Flame"],
  ["Mirror",          "Glass"],
  ["Clock",           "Time"],
  ["Flashlight",      "Beam"],
  ["Freezer",         "Cold"],
  ["Glove",           "Hand"],
  ["Hourglass",       "Sand"],
  ["Kettle",          "Boil"],
  ["Toothbrush",      "Bathroom"],
  ["Soap",            "Clean"],
  ["Shampoo",         "Hair"],
  ["Toilet",          "Bathroom"],
  ["Bed",             "Sleep"],
  ["Pillow",          "Cushion"],
  ["Blanket",         "Cozy"],
  ["Refrigerator",    "Cold"],
  ["Oven",            "Kitchen"],
  ["Microwave",       "Heat"],
  ["Fan",             "Cool"],
  ["Air Conditioner", "Cold"],
  ["Couch",           "Living Room"],
  ["Bookshelf",       "Library"],
  ["Desk Lamp",       "Light"],
  ["Curtains",        "Window"],
  ["Doormat",         "Welcome"],
  ["Trash Can",       "Waste"],
  ["Recycle Bin",     "Plastic"],
  ["Toaster",         "Bread"],
  ["Coffee Mug",      "Drink"],
  ["Spoon",           "Soup"],
  ["Fork",            "Dinner"],
  ["Knife",           "Sharp"],
  ["Frying Pan",      "Stove"],
  ["Dish Soap",       "Sink"],
  ["Sponge",          "Clean"],
  ["Toothpaste",      "Mint"],
  ["Towel",           "Dry"],
  ["Hairdryer",       "Air"],
  ["Hairbrush",       "Tangle"],
  ["Shower",          "Water"],
  ["Tissue",          "Box"],
  ["Alarm Clock",     "Morning"],

  // ─── TOOLS, CONSTRUCTION & GARDEN ───────────────────────
  ["Hammer",          "Nail"],
  ["Saw",             "Cut"],
  ["Wrench",          "Bolt"],
  ["Screwdriver",     "Screw"],
  ["Toolbox",         "Tools"],
  ["Ladder",          "Climb"],
  ["Paintbrush",      "Paint"],
  ["Bucket",          "Carry"],
  ["Shovel",          "Dig"],
  ["Wheelbarrow",     "Garden"],
  ["Garden",          "Plants"],
  ["Bulldozer",       "Construction"],
  ["Carpenter",       "Wood"],
  ["Crane",           "Lift"],
  ["Generator",       "Electricity"],
  ["Jackhammer",      "Drill"],

  // ─── PLANTS & FLOWERS ───────────────────────────────────
  ["Rose",            "Flower"],
  ["Tulip",           "Spring"],
  ["Sunflower",       "Yellow"],
  ["Lily",            "Bloom"],
  ["Treehouse",       "Branches"],
  ["Pinecone",        "Forest"],
  ["Leaf",            "Autumn"],

  // ─── CLOTHING & ACCESSORIES ─────────────────────────────
  ["Wedding",         "Ring"],
  ["Diamond",         "Sparkle"],
  ["Bracelet",        "Jewelry"],
  ["Locket",          "Photo"],
  ["Sunglasses",      "Shade"],
  ["Raincoat",        "Wet"],
  ["Slippers",        "House"],
  ["Pyjamas",         "Bed"],
  ["Umbrella",        "Shield"],
  ["Wallet",          "Pocket"],
  ["Keyring",         "Keys"],

  // ─── MISCELLANEOUS MISC ─────────────────────────────────
  ["Campfire",        "Smoke"],
  ["Lantern",         "Light"],
  ["Midnight",        "Dark"],
  ["Treasure",        "Gold"],
  ["Sunrise",         "Dawn"],
  ["Sandbox",         "Play"],
  ["Firefly",         "Glow"],
  ["Windmill",        "Breeze"],
  ["Scarecrow",       "Field"],
  ["Cobweb",          "Spider"],
  ["Pendulum",        "Swing"],
  ["Coral",           "Reef"],
  ["Barsha",          "Monsoon"],
  ["Barsat",          "Rainy Season"],
  ["Loo",             "Hot Wind"],
  ["Hiund",           "Winter"],
  ["Daydream",        "Imagine"],
  ["Rato Mato",       "Red Clay"],
  ["Bari",            "Field"],
  ["Khet",            "Muddy"],
  ["Asala Fish",      "Cold Water"],
  ["Barrel",          "Wood"],
  ["Binoculars",      "Distance"],
  ["Blueprint",       "Design"],
  ["Boomerang",       "Return"],
  ["Crystal",         "Shine"],
  ["Mailbox",         "Letters"],
  ["Marble",          "Stone"],
  ["Postcard",        "Mail"],
  ["Soltee",          "Friend"],
  ["Daju",            "Brother"],
  ["Didi",            "Sister"],
  ["Money",           "Cash"],
  ["Credit Card",     "Payment"],
  ["Bank",            "Finance"],
  ["Shopping Mall",   "Stores"],
  ["Supermarket",     "Groceries"],
  ["Chef",            "Kitchen"],

  // ─── NEPALESE PLACES & LANDMARKS ────────────────────────
  ["Mount Everest",   "Mountain"],
  ["Kathmandu",       "City"],
  ["Pokhara",         "Lake"],
  ["Pashupatinath",   "River"],
  ["Boudhanath",      "Eyes"],
  ["Lumbini",         "Peace"],
  ["Gorkha",          "Brave"],
  ["Annapurna",       "Trek"],
  ["Machapuchare",    "Peak"],
  ["Fewa Lake",       "Water"],
  ["Rara Lake",       "Blue"],
  ["Terai",           "Flat"],
  ["Himalayas",       "Snow"],
  ["Mustang",         "Desert"],
  ["Namche Bazaar",   "Market"],
  ["Chitwan",         "Jungle"],
  ["Sagarmatha",      "Highest"],
  ["Koshi River",     "Flow"],
  ["Tilicho Lake",    "Altitude"],
  ["Kali Gandaki",    "Gorge"],
  ["Swayambhunath",   "Monkey"],
  ["Patan Durbar",    "Palace"],
  ["Bhaktapur",       "Brick"],
  ["Janaki Mandir",   "White Temple"],
  ["Ghandruk",        "Village"],
  ["Bandipur",        "Old Town"],
  ["Nagarkot",        "Viewpoint"],
  ["Dhulikhel",       "Hills"],
  ["Manang",          "Highland"],
  ["Lantang",         "Valley"],
  ["Kanchenjunga",    "Glacier"],
  ["Godawari",        "Garden"],
  ["Kakani",          "Hill Station"],
  ["Muktinath",       "Cold Shower"],
  ["Shey Phoksundo",  "Blue Lake"],
  ["Tea Garden",      "Hills"],

  // ─── NEPALESE CUISINE ───────────────────────────────────
  ["Momo",            "Nepali Culture"],
  ["Dal Bhat",        "Lentil"],
  ["Sel Roti",        "Ring"],
  ["Gundruk",         "Fermented"],
  ["Yomari",          "Sweet"],
  ["Chhurpi",         "Milk"],
  ["Sukuti",          "Dried Meat"],
  ["Tongba",          "Warm Drink"],
  ["Masala Chia",     "Spices"],
  ["Lassi",           "Yogurt"],
  ["Puri Tarkari",    "Breakfast"],
  ["Panipuri",        "Street Food"],
  ["Thakali Thali",   "Platter"],
  ["Pustakari",       "Hard Candy"],
  ["Raksi",           "Alcohol"],
  ["Chhaang",         "Milky Brew"],

  // ─── NEPALESE FLORA, FAUNA & WILDLIFE ───────────────────
  ["Rhino",           "Horn"],
  ["Yak",             "Hairy"],
  ["Rhododendron",    "Red Flower"],
  ["Danfe",           "Feathers"],
  ["Bengal Tiger",    "Stripes"],
  ["Snow Leopard",    "Ghost"],
  ["Red Panda",       "Tail"],
  ["Yartsa Gunbu",    "Caterpillar"],
  ["Marigold",        "Garland"],

  // ─── NEPALESE CULTURE, TRADITIONS & RITUALS ─────────────
  ["Sherpa",          "Climb"],
  ["Chautari",        "Tree"],
  ["Khukuri",         "Blade"],
  ["Suspension Bridge","River"],
  ["Prayer Flag",     "Wind"],
  ["Kumari",          "Goddess"],
  ["Stupa",           "Dome"],
  ["Pagoda",          "Roof"],
  ["Mani Wheel",      "Spin"],
  ["Incense",         "Smoke"],
  ["Tika",            "Forehead"],
  ["Namaste",         "Greeting"],
  ["Bhajan",          "Song"],
  ["Gumba",           "Monastery"],
  ["Gunyou Cholo",    "Dress"],
  ["Daura Suruwal",   "Formal"],
  ["Haku Patasi",     "Black Sari"],
  ["Doko",            "Basket"],
  ["Nanglo",          "Flat"],
  ["Karuwa",          "Vessel"],
  ["Gagun",           "Water Pot"],
  ["Gurung",          "Hills Tribe"],
  ["Tamang",          "Highlander"],
  ["Tharu",           "Plains Tribe"],
  ["Rai",             "Eastern Tribe"],
  ["Bhanubhakta",     "Poet"],
  ["Lakhey",          "Dance"],
  ["Jhankri",         "Magic"],

  // ─── NEPALESE FESTIVALS & UTILITIES ──────────────────────
  ["Dashain",         "Festival"],
  ["Tihar",           "Lights"],
  ["Holi",            "Colors"],
  ["Teej",            "Red Dress"],
  ["Chhath",          "Sun"],
  ["Lhosar",          "New Year"],
  ["Gai Jatra",       "Cow"],
  ["Deusi Bhailo",    "Singing"],
  ["Janto",           "Grind"],
  ["Gagri",           "Clay Pot"],
  ["Madani",          "Churn"],
  ["Namlo",           "Strap"],
  ["Chulo",           "Stove"],

  // ─── NEPALESE MUSICAL INSTRUMENTS ───────────────────────
  ["Sarangi",         "Strings"],
  ["Madal",           "Beat"],
  ["Panche Baja",     "Band"],
  ["Flute",           "Woodwind"],
  ["Damphu",          "Drum"],
];